services:
  - type: web
    name: racines-app-back
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./racines-app-back
    plan: free
    region: oregon
    envVars:
      - key: JAVA_OPTS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: 8080
      - key: APP_BASE_URL
        value: https://racines-app-back.onrender.com
      - key: APP_FRONTEND_URL
        value: https://racines-app-front.vercel.app
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://racines-app-front.vercel.app,http://localhost:4200
      - key: APP_MAIL_PROVIDER
        value: brevo
      - key: APP_MAIL_FROM
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
